apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: utils
spec:
  containers:
  - name: debug
    image: quay.io/marcocaimi/ocp-debug-ubi8:ubi8
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      runAsUser: 0
    tty: true
    stdin: true
    volumeMounts:
      - mountPath: /host
        name: host
  restartPolicy: Always
  volumes:
    - hostPath:
        path: /
        type: Directory
      name: host
