---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kafka-event-producer
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/kafka-event-producer-demo/event-producer
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kafka-event-producer-github-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/mcaimi/kafka-event-producer-demo
  - name: revision
    value: master
